const assert=require('node:assert/strict');
const {loadAndValidate,validateDocuments}=require('../validate/validate_content_configs');
const {schema,documents,errors}=loadAndValidate();
assert.deepEqual(errors,[],errors.join('\n'));
const clone=()=>structuredClone(documents);
let invalid=clone(); invalid['res://data/skills/skills.json'].skills[0].type='attack';
assert(validateDocuments(invalid,schema).some(e=>e.includes('.type: unknown')),'old skill alias rejected');
invalid=clone();invalid['res://data/skills/skills.json'].skills.push(structuredClone(invalid['res://data/skills/skills.json'].skills[0]));
assert(validateDocuments(invalid,schema).some(e=>e.includes('duplicate ID')),'duplicate IDs rejected');
invalid=clone();invalid['res://data/characters/characters.json'].characters[0].starting_skill_id='missing_skill';
assert(validateDocuments(invalid,schema).some(e=>e.includes('unknown skills reference')),'missing cross-domain reference rejected');
invalid=clone();invalid['res://data/skills/skills.json'].skills[0].max_level='5';
assert(validateDocuments(invalid,schema).some(e=>e.includes('.max_level: invalid type')),'wrong value types rejected');
invalid=clone();invalid['res://data/enemies/enemies.json'].monsters[0].base_stats.max_hp=-1;
assert(validateDocuments(invalid,schema).some(e=>e.includes('negative max_hp')),'invalid numeric range rejected');
assert(validateDocuments(documents,schema,()=>false).some(e=>e.includes('missing resource')),'missing resource paths rejected');
invalid=clone();invalid['res://data/enemies/enemies.json'].monsters[0].base_stats.max_hp='broken-number';
assert(validateDocuments(invalid,schema).length>0,'nested numeric base stats rejected');
invalid=clone();delete invalid['res://data/enemies/enemies.json'].monsters[0].base_stats.contact_interval;
assert(validateDocuments(invalid,schema).length>0,'mandatory nested fields required');
invalid=clone();invalid['res://data/relics/relics.json'].relics[0].modifiers[0].stat=42;
invalid['res://data/relics/relics.json'].relics[0].modifiers[0].source='';
assert(validateDocuments(invalid,schema).length>0,'modifier strings required');
invalid=clone();invalid['res://data/waves/waves.json'].waves[0].groups[0].enemy_ids=['missing_enemy'];
assert(validateDocuments(invalid,schema).length>0,'wave enemy references validated');
invalid=clone();invalid['res://data/skills/skills.json'].skills[0].school='missing_god';
assert(validateDocuments(invalid,schema).length>0,'skill school references validated');
invalid=clone();invalid['res://data/summons/summons.json'].summons[0].scene_path='not-a-real-scene.tscn';
assert(validateDocuments(invalid,schema).length>0,'malformed resource paths rejected');
console.log('Content validation failure cases passed.');
