const assert=require('node:assert/strict');
const {summarize,normalizeAssistMetadata}=require('./analyze_monster_combat');
const base={character:'mage',map:'abandoned_dungeon',build_index:0,seed:618,status:'AUTOMATED_RESULT_DEFEAT',duration_seconds:20,survival_assist:false,sampling_time_scale:1,flow_assisted_kills:0,player_attacks_disabled:false,initial_player:{max_health:75},summary:{damage_taken_total:10},enemy_observations:[]};
let result=summarize([base]);
assert.equal(result.cases,1);
assert.equal(result.outcomes.AUTOMATED_RESULT_DEFEAT,1);
assert.equal(result.issues.length,0,'death is an observation, not an engine failure');
assert.equal(result.conditions[0].median_seconds,20,'read the real JSON duration field');
assert.deepEqual(result.conditions[0].range_seconds,[20,20]);
assert.ok(summarize([{...base,duration_seconds:null}]).issues.some(x=>x.includes('duration')));
assert.ok(summarize([{...base,survival_assist:true}]).issues.some(x=>x.includes('assistance')));
assert.ok(summarize([base,base]).issues.some(x=>x.includes('duplicate')));
assert.ok(summarize([{...base,sampling_time_scale:16}]).issues.some(x=>x.includes('assistance')));
assert.ok(summarize([{...base,initial_player:{max_health:100000}}]).issues.some(x=>x.includes('health')));
assert.ok(summarize([{...base,enemy_observations:[{outcome:'self_death',ttk_seconds:1}]}]).issues.some(x=>x.includes('TTK')));
const raw={...base,survival_assist:true,sampling_scope:'normal-health automated combat; fixed 60 Hz, time scale 1; not human win rate'};
const normalized=normalizeAssistMetadata(raw,'E:/codex/test.json','source-hash');
assert.equal(raw.survival_assist,true,'preserve raw evidence');
assert.equal(normalized.survival_assist,false);
assert.equal(normalized.metadata_correction.source_sha256,'source-hash');
assert.throws(()=>normalizeAssistMetadata({...raw,sampling_time_scale:16},'',''));
assert.throws(()=>normalizeAssistMetadata({...raw,initial_player:{max_health:100000}},'',''));
console.log('[monster_combat_analysis] PASS');
