const COMPONENT_TYPES = ["cooldown", "targeting", "persistent_orbit"];

const TARGETING_MODES = [
  "self",
  "nearest_enemy",
  "highest_hp_enemy",
  "random_enemy",
  "random_enemies_around_player",
  "around_player",
];

const TARGETING_RULE_IDS = [
  "self",
  "nearest_enemy",
  "highest_hp_enemy",
  "random_enemy",
  "random_enemies_around_player",
  "around_player",
  "near_player",
];

const EVENT_TRIGGERS = ["on_cast", "on_projectile_hit", "on_orbit_hit", "on_trap_hit", "on_trap_expired"];

const DAMAGE_ORIGINS = [
  "primary_attack",
  "status_dot",
  "reaction",
  "field",
  "trap",
  "special",
  "healing",
];

const MODIFIER_KEYS = [
  "attack_speed_multiplier_add",
  "boss_burn_max_stacks_add",
  "burn_damage_multiplier_add",
  "burn_duration_add",
  "burn_max_stacks_add",
  "burn_move_speed_multiplier_add_per_stack",
  "break_damage_multiplier_add",
  "damage_multiplier_add",
  "direct_damage_multiplier_add",
  "explosion_damage_multiplier_add",
  "explosion_max_targets_add",
  "explosion_radius_multiplier_add",
  "lava_duration_add",
  "lava_radius_multiplier_add",
  "max_active_traps_add",
  "pierce_add",
  "pierce_override",
  "projectile_count_add",
  "projectile_speed_multiplier_add",
  "range_multiplier_add",
  "shield_value_add",
  "skill_area_multiplier_add",
];

const SPECIAL_RULE_KEYS = [
  "burning_target_death_explosion",
  "burn_target_burst_explosion_damage_bonus",
  "boss_poise_upgrade",
  "chain_end_burst",
  "chain_new_target_damage_ramp",
  "cloud_arrow_every_n_casts",
  "cross_relic_base",
  "cross_relic_dot_target_damage_bonus",
  "cross_relic_echo_every_n_ticks",
  "cross_relic_echo_targeting",
  "cross_relic_echo_upgrade",
  "cross_relic_faith_judgement",
  "cross_relic_field_capacity",
  "cross_relic_field_damage_reduction",
  "cross_relic_field_heal_upgrade",
  "cross_relic_impurity_on_field_tick",
  "cross_relic_low_hp_rescue",
  "cross_relic_periodic_shield",
  "cross_relic_purify_boss_poise",
  "cross_relic_purify_dot",
  "cross_relic_purify_impurity",
  "cross_relic_purify_small_pulse",
  "cross_relic_purify_upgrade",
  "cross_relic_shelter_upgrade",
  "cross_relic_stand_shield",
  "boss_core_focus",
  "boss_core_trap_bonus_damage",
  "arcane_double_page_every_n_casts",
  "arcane_seal_burst",
  "arcane_seal_burst_elite_boss_bonus",
  "arcane_seal_burst_vulnerability",
  "arcane_seal_duration_add",
  "arcane_seal_on_elite_boss_hit",
  "arcane_page_copy_on_hit",
  "bleed_moving_target_bonus",
  "bleed_on_crit_wound",
  "boss_low_hp_execution_burst",
  "burst_mark_death_explosion",
  "burst_mark_on_arrow_explosion",
  "chain_trap_root_on_hit",
  "direct_hit_extra_explosion_bonus",
  "decoy_boss_core_bonus",
  "decoy_trap_explosion",
  "decoy_trap_spawn",
  "decoy_trap_upgrade",
  "explosion_direct_hit_burn_on_elite_boss",
  "explosion_multi_hit_burn",
  "flame_core_boss_burst",
  "flame_core_duration_add",
  "flame_core_full_stack_explosion_vulnerability",
  "flame_core_on_elite_boss_direct_hit",
  "extra_knife_every_n_casts",
  "ground_fire_on_hit",
  "freeze_frostbite_near_player",
  "frost_lock_bonus_hit",
  "frost_lock_on_elite_boss_direct_hit",
  "frostbite_freeze_or_poise",
  "frostbite_on_hail_hit",
  "frost_aura_slow",
  "frost_core_crack_on_boss_poise",
  "frost_ring_on_player_damaged",
  "hail_same_target_decay",
  "hunter_arrow_explosion_mark",
  "hunter_arrow_explosion_upgrade",
  "hunter_arrow_hit_explosion",
  "hunter_arrow_pierce_tuning",
  "hunter_arrow_shards_after_pierce_hits",
  "hunter_mark_primary_damage_taken",
  "hunter_mark_tuning",
  "hunter_snare_on_strong_trap_hit",
  "hunter_trap_targeting",
  "holy_counter_boss_poise",
  "holy_counter_on_marked_break_hit",
  "holy_mark_holy_vulnerability",
  "holy_mark_nearest_pulse_target",
  "holy_mark_on_strong_pulse_hit",
  "holy_mark_pulse_focus",
  "holy_mark_tuning",
  "holy_pulse_interval",
  "holy_pulse_radius",
  "holy_shield_base",
  "holy_shield_break_damage_reduction",
  "holy_shield_break_shockwave",
  "holy_shield_contact_damage_reduction",
  "holy_shield_expire_heal",
  "holy_shockwave_every_n_pulses",
  "judgement_beam_on_boss_mark_pulses",
  "hot_rapid_fire",
  "forbidden_boss_stack",
  "forbidden_page_every_n_casts",
  "forbidden_page_risk",
  "forbidden_page_upgrade",
  "deflagration_apply_burn",
  "deflagration_upgrade",
  "burn_in_merged_oil",
  "flammable_burst_boss_poise",
  "flammable_mark_boss_tuning",
  "flammable_mark_burst_on_full_mark_tick",
  "flammable_mark_fire_vulnerability",
  "flammable_mark_on_strong_oil_tick",
  "fire_oil_burn_damage_in_big_oil",
  "fire_oil_canister_base",
  "fire_oil_duration_tuning",
  "fire_oil_merge_upgrade",
  "fire_oil_merge_zones",
  "full_oil_secondary_deflagration",
  "lava_slow",
  "lightning_chain_bounce",
  "low_hp_damage_bonus",
  "magnetic_storm_on_shock_consume",
  "marked_hit_cooldown_refund",
  "marked_target_death_explosion",
  "orbit_before_launch",
  "orbit_contact_damage",
  "orbit_contact_slow",
  "orbit_guard_extra_orb",
  "overload_on_voltage",
  "overload_shock_lightning",
  "oil_stack_on_fire_oil_tick",
  "oil_fire_deflagration",
  "page_spirit_attack",
  "page_spirit_intercept",
  "page_spirit_remote_damage_reduction",
  "page_spirit_spawn",
  "player_lava_on_nearby_fireball_hit",
  "protective_lava_ring_on_player_damaged",
  "recycle_dash_buff",
  "recycle_knife_on_normal_kill",
  "recycle_knife_upgrade",
  "same_target_multi_projectile_damage",
  "same_target_short_window_decay",
  "small_trap_on_trigger",
  "small_trap_upgrade",
  "shatter_kill_spawn_icicle",
  "shatter_on_freeze_or_frost_hit",
  "shatter_upgrade",
  "shock_consume_reaction",
  "shock_on_lightning_orb_hit",
  "shock_upgrade",
  "smoke_cloud_on_oil_expire",
  "smoke_cloud_on_player_damaged",
  "smoke_enemy_damage_down",
  "smoke_player_speed_buff",
  "soulburn_burst_on_full_burn_direct_hit",
  "soul_ember_on_direct_hit",
  "soul_ember_to_burn_on_full_stack_hit",
  "storm_hail_every_n_casts",
  "trap_explosion_upgrade",
  "trap_hit_explosion",
  "trap_kill_fragment_field",
  "trap_radius_upgrade",
  "antidote_cloud_on_low_hp",
  "acid_mark_on_strong_acid_tick",
  "acid_mark_vulnerability",
  "acid_burst_cooldown_tuning",
  "acid_burst_damage_tuning",
  "acid_burst_high_defense_bonus",
  "acid_burst_on_full_acid_mark_hit",
  "acid_burst_on_full_acid_residue_hit",
  "acid_burst_spread_residue",
  "acid_hit_shield",
  "acid_pressure_duration_damage",
  "acid_pressure_every_n_casts",
  "acid_pressure_range_width",
  "acid_pressure_tick_interval",
  "acid_sprayer_base",
  "acid_residue_on_acid_tick",
  "boss_acid_mark_armor_break_pulse",
  "corrosive_film_nearby_acid_mark",
  "corrosive_film_on_boss_skill_hit",
  "corrosive_film_upgrade",
  "full_poison_death_explosion",
  "poison_on_cloud_tick_chance",
  "poison_cloud_edge_speed_buff",
  "poison_cloud_enemy_damage_down",
  "poison_cloud_slow",
  "poison_death_explosion",
  "poison_death_explosion_upgrade",
  "poison_elite_boss_tuning",
  "poison_max_stack_tuning",
  "toxic_core_boss_pulse",
  "toxic_core_on_strong_cloud_tick",
  "toxic_core_to_poison",
  "toxin_seed_on_poison_cloud_tick",
  "toxin_seed_to_poison",
  "toxic_vial_base",
  "toxic_vial_small_cloud_cooldown",
  "toxic_vial_small_cloud_on_poison_kill",
  "toxic_vial_small_cloud_upgrade",
  "eagle_shot_on_boss_mark_hits",
  "eagle_mark_on_strong_hit",
  "eagle_mark_primary_damage_taken",
  "eagle_marked_hit_cooldown_refund",
  "eagle_shot_on_boss_eagle_mark_hits",
  "unused_bounce_to_elite_boss_damage",
  "voltage_on_elite_boss_hit",
  "windstep_double_arrow",
  "windstep_projectile_speed",
  "windstep_state",
  "execution_mark_crit_damage_taken",
  "execution_mark_on_strong_target",
  "next_knife_damage_after_kill",
  "pincer_reaction_on_root",
  "prey_mark_on_strong_trap_hit",
  "rupture_on_full_wound_crit",
  "wound_on_throwing_knife_hit",
  "wound_tuning",
  "judgment_tuning",
  "judgment_on_strong_hit",
  "warhammer_base",
  "warhammer_boss_low_hp_shockwave",
  "warhammer_boss_poise_judgement_bonus",
  "warhammer_crack_field",
  "warhammer_crack_upgrade",
  "warhammer_forced_shock_every_n_seconds",
  "warhammer_judgement_shock",
  "warhammer_judgement_shock_upgrade",
  "warhammer_knockback_multiplier",
  "warhammer_low_hp_damage_bonus",
  "warhammer_quake_slam_every_n_casts",
  "warhammer_stun_on_hit",
  "warhammer_stun_target_damage_taken",
];

const DAMAGE_PACKET_PARAMS = [
  "amount",
  "can_crit",
  "can_trigger_reaction",
  "crit_chance_add",
  "crit_damage_add",
  "damage",
  "damage_origin",
  "damage_type",
  "element",
  "field_damage_model",
  "ignore_defense",
  "ignore_min_damage",
  "ignore_resistance",
  "ignore_vulnerability",
  "reaction_depth",
  "share_primary_attack_crit",
  "source_id",
  "source_instance_id",
  "special_final_modifier",
  "special_final_modifier_source",
  "special_rule_tags",
  "uses_character_damage_multiplier",
  "uses_skill_level_coefficient",
];

const STATUS_PARAMS = [
  "chance",
  "duration",
  "max_stacks",
  "stack",
  "status_damage",
  "status_duration",
  "status_id",
  "status_on_hit",
  "status_normal_only",
  "status_params",
  "status_tick_interval",
  "statuses_on_hit",
  "tick_interval",
];

const VISUAL_PARAMS = [
  "visual_color",
  "visual_mode",
  "visual_ring_color",
  "visual_style",
];

const ACTION_CONTRACTS = {
  deal_damage: {
    allowedParams: DAMAGE_PACKET_PARAMS,
  },
  apply_status: {
    allowedParams: ["chance", "damage", "duration", "max_stacks", "stack", "status_id", "tick_interval"],
    requiredParams: ["status_id"],
  },
  spawn_projectile: {
    allowedParams: [
      ...DAMAGE_PACKET_PARAMS,
      ...STATUS_PARAMS,
      "collision_radius",
      "count",
      "curve_height",
      "damage_multiplier_sequence",
      "lifetime",
      "object_id",
      "pierce",
      "projectile_id",
      "radius",
      "spawn_offset",
      "speed",
      "spread_angle",
      "trajectory_mode",
      ...VISUAL_PARAMS,
    ],
    requiredAnyParams: [["projectile_id", "object_id", "source_id"]],
    combatObjectParam: ["projectile_id", "object_id", "source_id"],
  },
  spawn_projectiles_at_targets: {
    allowedParams: [
      ...DAMAGE_PACKET_PARAMS,
      ...STATUS_PARAMS,
      "collision_radius",
      "count",
      "curve_height",
      "damage_multiplier_sequence",
      "lifetime",
      "object_id",
      "pierce",
      "projectile_id",
      "radius",
      "range",
      "spawn_offset",
      "speed",
      "targeting_mode",
      "trajectory_mode",
      ...VISUAL_PARAMS,
    ],
    requiredAnyParams: [["projectile_id", "object_id", "source_id"]],
    combatObjectParam: ["projectile_id", "object_id", "source_id"],
  },
  spawn_area: {
    allowedParams: [
      ...DAMAGE_PACKET_PARAMS,
      ...STATUS_PARAMS,
      "area_id",
      "collision_radius",
      "cone_direction",
      "cone_width_degrees",
      "damage_once_per_body",
      "event_on_expire",
      "event_on_hit",
      "expand_from_radius",
      "expand_to_radius",
      "finish_after_damage",
      "max_active",
      "max_targets",
      "object_id",
      "position",
      "position_mode",
      "radius",
      ...VISUAL_PARAMS,
    ],
    combatObjectParam: ["area_id", "object_id"],
  },
  create_explosion: {
    allowedParams: [
      ...DAMAGE_PACKET_PARAMS,
      ...STATUS_PARAMS,
      "area_id",
      "collision_radius",
      "damage_once_per_body",
      "damage_multiplier",
      "event_on_hit",
      "expand_from_radius",
      "expand_to_radius",
      "impact_target_damage_multiplier",
      "max_targets",
      "object_id",
      "position",
      "position_mode",
      "radius",
      ...VISUAL_PARAMS,
    ],
    combatObjectParam: ["area_id", "object_id"],
  },
  spawn_trap: {
    allowedParams: [
      ...DAMAGE_PACKET_PARAMS,
      ...STATUS_PARAMS,
      "area_id",
      "collision_radius",
      "damage_once_per_body",
      "event_on_expire",
      "event_on_hit",
      "expand_from_radius",
      "expand_to_radius",
      "finish_after_damage",
      "max_active",
      "max_targets",
      "object_id",
      "position",
      "position_mode",
      "radius",
      ...VISUAL_PARAMS,
    ],
    combatObjectParam: ["area_id", "object_id"],
  },
  spawn_orbit_object: {
    allowedParams: [
      ...DAMAGE_PACKET_PARAMS,
      "collision_radius",
      "count",
      "follow_owner",
      "hit_interval",
      "object_id",
      "orbit_radius",
      "rotation_speed",
    ],
    requiredAnyParams: [["object_id", "source_id"]],
    combatObjectParam: ["object_id", "source_id"],
  },
  chain_to_targets: {
    allowedParams: [
      ...DAMAGE_PACKET_PARAMS,
      ...STATUS_PARAMS,
      "actions",
      "count",
      "max_targets",
      "radius",
      "target_group",
    ],
  },
  consume_status_stack: {
    allowedParams: ["stack", "stacks", "status_id"],
    requiredParams: ["status_id"],
  },
  damage_by_status_stack: {
    allowedParams: [
      ...DAMAGE_PACKET_PARAMS,
      "amount_per_stack",
      "consume",
      "consume_stacks",
      "damage_per_stack",
      "status_id",
      "status_ids",
    ],
    requiredAnyParams: [["status_id", "status_ids"]],
  },
  knockback: {
    allowedParams: ["force"],
  },
  heal_owner: {
    allowedParams: ["amount"],
  },
  heal_caster: {
    allowedParams: ["amount"],
  },
  destroy_enemy_projectile: {
    allowedParams: ["radius"],
  },
  add_temporary_modifier: {
    allowedParams: ["duration", "modifiers", "source_id"],
  },
};

const COMPONENT_CONTRACTS = {
  cooldown: {
    allowedParams: ["seconds"],
  },
  targeting: {
    allowedParams: ["count", "mode", "radius", "range"],
  },
  persistent_orbit: {
    allowedParams: ACTION_CONTRACTS.spawn_orbit_object.allowedParams,
    combatObjectParam: ACTION_CONTRACTS.spawn_orbit_object.combatObjectParam,
  },
};

module.exports = {
  ACTION_CONTRACTS,
  COMPONENT_CONTRACTS,
  COMPONENT_TYPES,
  DAMAGE_ORIGINS,
  EVENT_TRIGGERS,
  MODIFIER_KEYS,
  SPECIAL_RULE_KEYS,
  TARGETING_MODES,
  TARGETING_RULE_IDS,
};
